### ISSUE TITLE
Pit Menu options available only when In Car Rotary on 'Pit'

### ISSUE THREAD

**Issue by mcowger** [andreasdahl1987/DahlDesignProperties#1]
Hi @andreasdahl1987 -

I'm curious about the reasoning behind the decision to only allow the pit menu actions to be available when the in car rotary is set to "Pit"?

It seems like they are not necessarily linked, except in the case of an 'overloaded' FunkySwitch being used for both.  Maybe an example is helpful:

I have 2 rotaries on my wheel, L and R.   Each of those rotaries has a conveniently placed up/down momentary, and L has a button thats perfect for 'OK'.

I'm not sure why I can't map the L rotary to PitMenu positions and the appropriate up/down/ok to appropriate buttons, and active them independent of what the In-Car rotary is doing.

Can you help me understand this reasoning?

**Comment by andreasdahl1987** [comment]
Hi @mcowger !

I decided to go with a system where you can use the same buttons for "+", "-" and "ok" for both menus. In that case, if you're binding stuff to all 12 positions, you'd fire off commands/bindings from both menus when pressing "+", "-", "ok" (likely depending a bit on the sim, might be firing on the menu for the rotary that most recently changed position). This would be a bit messy. Your inCar is set to energyDeploy and your pitMenu is set to 4Tires, you wont know what will happen when you press "+". So the solution was to keep he 12th position in the inCar menu as an inactive position, where the pitMenu will take over. This system also determines what to be shown in the menu box in the Dahl Design Dashboard. 

I know, it is a bit inconvenient. DDC software has great synergy with this system though. Both the DDS functions and the Multicomplex functions. 

I could of course add an option to map seperate "+" and "-" buttons, which would work well for a setup like yours, and in that case disable the inCar menu graphics in the dashboard. 

Suggestions?

**Comment by mcowger** [comment]
>DDC software has great synergy with this system though

It does, and I totally understand now why you took this route.

>I could of course add an option to map seperate "+" and "-" buttons

I think thats a pretty reasonable option.

>and in that case disable the inCar menu graphics in the dashboard.

Why would we disable the graphic in the dash in that case?  I dont see why we'd have to get rid of it?

**Comment by andreasdahl1987** [comment]
No, wouldn't need to get rid of it. Could make a property that reflects which menu that had the most recent change in position - and show that one in the dashboard.
