### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by photon1503** [andreasdahl1987/DahlDesignProperties#15]
Hi @andreasdahl1987 @mcowger 

tonight I refactored the code a little bit.

- Moved iRacing stuff to Sections\iRacing.cs
- Moved DDC to Sections\DDC.cs
- Move all other dashboard related things to Sections\Dashboard.cs
- Weight loss of main program DataPluginDemo.cs is from > 7K lines to skinny 127 lines

No functionality has been changed or added, I made a short test and it works like before on my system.

Main reason for the refactoring is better maintainability and extensibility for future releases.

Please have a look at https://github.com/photon1503/DahlDesignProperties?organization=photon1503&organization=photon1503  and let me know your thoughts.

**Comment by andreasdahl1987** [comment]
This looks really good @photon1503 ! I'll need time to look into the changes you made, but firsy glance it is definitely a lot more managable that before:D Im not surprised that you felt the need to refractor the project, @mcowger is working on the same thing, but in that case more of a total rewrite - which will take a lot of time, testing and understanding (on my part) to finish. 

Im away at a wedding this weekend, but then Ill dig into it. As none of the algorithms are changed here, Im assuming this will work just like before, just better organized. So we'll merge when Ive understood what youve done 😄 Great work!

**Comment by andreasdahl1987** [comment]
@photon1503 Can you make a pull request, so that we can try moving over to the layout you made? Could we try changing some naming in the same process? See what I did in the 'dev' branch. It didnt work, crashed spectacularly when trying to make a shortcut to the plugin on the left and side. SimHub log seemed to react to the icon bitmap file, I couldnt figure it out 😢

**Comment by photon1503** [comment]
@andreasdahl1987 Currently pull request fails due to conflicts, but let me check.
Also building the solution in the cloud fails since the DLLs can't be found, no idea why. Locally it still works. 

Let me check your dev branch to see if I can integrate the changes

**Comment by photon1503** [comment]
Now it compiled successfully. I changed the paths for the DLLs and forgot to adopt the github action.
@andreasdahl1987  Please check if everything works as it should by downloading https://github.com/photon1503/DahlDesignProperties/releases/download/1.10.1/DahlDesign.dll
Since I don't have all the hardware, I can't test most of the features.

**Comment by photon1503** [comment]
@andreasdahl1987 - can't see what you have done in the dev branch, the last commit is 3 months ago

**Comment by andreasdahl1987** [comment]
@photon1503 Yes that is the one that I meant, the commit where I changed naming. I thought it would work, but crashed when checking the plugin for quick access on the left hand side menu in SimHub.

**Comment by photon1503** [comment]
now I get the point, yes we should rename the namespace from PluginSdkDemo to something proper :-)
But I will not change in in current PR, let's do it step by step

**Comment by andreasdahl1987** [comment]
> now I get the point, yes we should rename the namespace from PluginSdkDemo to something proper :-) But I will not change in in current PR, let's do it step by step

Allrighty :D

**Comment by andreasdahl1987** [comment]
Merged in #16
