### ISSUE TITLE
Activate Left/Right screen programmatically

### ISSUE THREAD

**Issue by photon1503** [andreasdahl1987/DahlDesignProperties#20]
@andreasdahl1987 and @mcowger 

In order to be able to change the current screen in the left and right screen widget, I tried to create a new property.

The goal is to define indivdual starting screens based on the current session (Practice, Quali, Race) and to keep the possiblity to switch through the screens with Action A/B and Action C/D.

But I'm failing already at the beginning ...

I created and assigned a new property to the following setting in the Dasboard designer (with indidivual conditions of course, and only one of them is true)

<img width="705" alt="image" src="https://user-images.githubusercontent.com/14548927/202903707-d6d2204d-6736-48a2-a776-5834d2aaff05.png">

The setting has zero influence to what screen is shown. I even unset the actions for next/previous screen but this didn't help too.

Any ideas?

**Comment by andreasdahl1987** [comment]
@photon1503 I havent tested this function in the dash editor. The text below the box might indicate that the use is not for overriding, but for not displaying? Have you tried setting conditions for all the screens?

**Comment by andreasdahl1987** [comment]
By the way, very cool that you started working on this 🙏

**Comment by photon1503** [comment]
Yes I set the condition in all screens but could not get it working. Let me see how to solve this, the doc for sim hub lacks a little bit

**Comment by photon1503** [comment]
But let's have some fun before! ![image](https://user-images.githubusercontent.com/14548927/202914623-b562a8aa-2448-4fc3-884e-b513e2c8cf0d.jpeg)

I really like the dashboard ☺️

**Comment by andreasdahl1987** [comment]
@photon1503 Have fun! I could also spend more time driving and less time typing 😅

**Comment by photon1503** [comment]
I did a little bit more research on the "Screen activation" option in SimHub Dash Editor. It's not possible to _select_ a dedicated screen, this setting is just for _enabling_ (or disabling) a screen as whole.

The communication between the C# plugin and the Dashboard is possibly only by using SimHub Properties, and the current screen name is neither exposed as property nor can be set .

Option 1 is to merge the different screens into one and to set the visibility of the layers with a binding. But this will make editing them even worse and we will loose the option to use the standard "ActionA-D" commands for NextScreen / PreviousScreen.

Option 2 is to somehow get an instance of the Dashboard in the plugin to gain direct access to the properties.

I'll now investigate Option 2 which will take some time

**Comment by andreasdahl1987** [comment]
Option 2 sound very cool, and always rewarding to explore new things! As for option 1, the editing part I agree with, as they are better off as individual screens. But when it comes to simhub action buttons, Ive actuallt gotten PMs from A LOT of users not finding out how to change the left and right pages. They've bound everything in the plugin menu but cant find a binding for these screens. It is the most common feedback I get from users. So I think actually having dedicated bindings to these pages could be a good idea. We could also make binding for specific page combinations. Imagine a multiposition switch that can go through a variety of dashboard setups; launch, map, practice, sector analysis, leader, catch up, qualy, hotlap, etc.

**Comment by photon1503** [comment]
@andreasdahl1987 
Option 2 is not really possible, the running Dashboard can't be accessed from the plugin.

But anyway I think you prefer Option 1 and moreover also want to have more control about the bindings.

I am thinking about the following approach:

Leave the Dashboard intact, but convert the single screens into Widgets. This will keep the nice maintenability but gives us finally a property for visibility for each single screen!

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/14548927/203172246-cb998dbb-23b4-4ef1-94c6-38a3d64745fc.png">

**Comment by andreasdahl1987** [comment]
@photon1503 Yes, that's a solid solution. Good overview and keeps all options for dash control open!

**Comment by photon1503** [comment]
found a solution, will submit a PR shortly
