### ISSUE TITLE
Redesign plugin menu

### ISSUE THREAD

**Issue by andreasdahl1987** [andreasdahl1987/DahlDesignProperties#25]
![image](https://user-images.githubusercontent.com/40788634/203303100-e1851bde-022e-4329-8f89-3246a7cd0c30.png)
Thinking of restructuring the plugin menu. More logical clustering of options, more tabs and having the tabs on the left hand side.

**Comment by photon1503** [comment]
@andreasdahl1987 
what do you think about this one? Simply using the standard style from SimHub, using the full width (automatically)

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/14548927/203387622-d99ff199-fbda-4f28-b8f5-4834e6ff86e4.png">

**Comment by andreasdahl1987** [comment]
@photon1503 I can't fault you on this, of course we should keep the same structure as SimHub has from before. Your suggestion is really good, full width is excellent. Looks like there is a scrollviewer on that page, so the reason why it is being cut is because the SimHub window needs to be 1080p tall? Is there a way to make this adaptive, or should we lower the height to 720p?

**Comment by photon1503** [comment]
There is no scrollbar in above screenshot, this is just some part of the border :-)
I removed the fixed height and width, we should not rely on any size of the screen. If the size becomes too small, now scrollbars are shown automatically.

With Scrollbar:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/14548927/203401650-9ec1a965-40d9-4912-864a-c333960a2901.png">

and without
<img width="691" alt="image" src="https://user-images.githubusercontent.com/14548927/203401738-2b4ce6fc-5980-4891-94f5-d3d7ab0db248.png">

**Comment by photon1503** [comment]
@andreasdahl1987 : BTW; while browsing through the XML file I noticed something. The toggle button SW1enabled is doubled. Guess I can delete the duplicate?
![image](https://user-images.githubusercontent.com/14548927/203402079-0973fe3e-e8da-4a88-afda-e129608bda14.png)

**Comment by photon1503** [comment]
could one of you please post screenshots of current "LED", "DDC" and "MISC" tabs? 
Messed up the XAML and would like to see how it looked before.
Thx!

**Comment by andreasdahl1987** [comment]
![image](https://user-images.githubusercontent.com/40788634/203404850-54cf0672-f2e4-4f1b-b629-27f1b46debf3.png)

**Comment by andreasdahl1987** [comment]
I think we should sort them like this, and in the following order:
- Dash settings (all settings for dashboard)
- Dash controls (all bindings for dashboard navigation)
- Car controls (all bindings for TC, Noboost, etc)
- Pit Menu (pit menu bindings as well as +/-/ok buttons and the PM messages)
- InCar Menu (incar menu bindings)
- Fuel and strategy (everything related to this)
- Controllers (DDC stuff)
- LED plugin (LED controls)
- Plugin Setup (Upshift/downshift bindings, I will also add the .js integration things here)
