### ISSUE TITLE
Session specific dash choices

### ISSUE THREAD

**Issue by andreasdahl1987** [andreasdahl1987/DahlDesignProperties#30]
@photon1503 Building on #20, what about instead of having an option for startup we'll have 3 options for practice (including warmup), qualys and race? The iRacing.cs has some logic for setting/resetting variables on session/car/track change.

**Comment by photon1503** [comment]
@andreasdahl1987 yes of course, this was also my intention. I just need to figure out how to get notified about session change?

**Comment by andreasdahl1987** [comment]
@photon1503 See #31

**Comment by andreasdahl1987** [comment]
Added in #31
