### ISSUE TITLE
Item change splash screen

### ISSUE THREAD

**Issue by photon1503** [andreasdahl1987/DahlDesignProperties#38]
In some dashboards we can see a big splash screen when some important values (BB, ABS, TC) are changed.

Should we also do something like this?
Sometimes I have a hard times reading the small numbers when i.e. changing BB

**Comment by andreasdahl1987** [comment]
Yeah it has been a request. 

I've added it car-specifically. For F1 cars, 919 and some others, not the GT3 cars. There is a splash widget in the dashboard. A "bug" with brake bias splash screen is that for some reason there is a glitch in BB telemetry when loading into the cockpit. So in some cases, when towing, entering the game, starting ignition, I see the splash screen popping up (using the changed() function in dashboard editor). So I was looking at this, trying to filter out this bug somehow, but havent givent it more thought. Shouldn't be too difficult. Maybe a cooldown timer after going out of `Idle` should do it. 

So adding splash screens for BB, engine map, ABS, TC1+2 perhaps? Maybe adjustments as well (wing, tape etc.) And add the option to chose which to use in the plugin menu? Default ON.

**Comment by photon1503** [comment]
Thank you for the comprehensive information. Didn't notice that there is already a splash screen, will have a look into into to make it (optionally) available for all cars. Maybe we can figure also out the bug and if not, implement some hysterisis

**Comment by photon1503** [comment]
Regarding the glitches, I can only assume that the splash screen shows up when i.e. entering the game, because the value jumps from zero or null to a valid value.

what about this?
``
(
if ([DataCorePlugin.CurrentGame]=='IRacing'
and (isnull([DataCorePlugin.GameRawData.Telemetry.EnterExitReset],0)>0
and isnull([DataCorePlugin.GameRawData.Telemetry.Voltage],1)>0
),1,0)
or [DataCorePlugin.CurrentGame]!='IRacing'
)
and
(
changed(1500,isnull([DataCorePlugin.GameData.NewData.BrakeBias],0))
or
changed(1500,isnull([DataCorePlugin.GameRawData.Telemetry.dcBoostLevel],0))
or
changed(1500,isnull([DataCorePlugin.GameData.NewData.TCLevel],0))
or
....//whatever
)
``

**Comment by photon1503** [comment]
Created a new "generic" slpash screen, which can be enabled in the Plugin options.

![image](https://user-images.githubusercontent.com/14548927/204144721-64c04809-8d33-4f2f-9f47-08cf5889d546.png)

Looks like this and will have text and value dynamically

![image](https://user-images.githubusercontent.com/14548927/204144738-7eddc0ae-05e9-4666-a99a-fe3c7445be94.png)

Currently it reacts on changes for the following properties

- TCCut
- EngineMap
- BrakeBias
- dcBoostLevel
- TCLevel
- dcTractionControl2
- dcTractionControl3
- dcTractionControl4
- ABSLevel
- dcMGUKDeployMode
- dcMGUKDeployFixed
- dcMGUKRegenGain
- dcAntiRollFront
- dcAntiRollRear
- dcDiffEntry
- dcDiffMiddle
- dcDiffExit
- dcDiffPreload
- dcWeightJackerRight
- dcFuelMixture
- dcPeakBrakeBias
- dcThrottleShape
- dcEngineBraking
- dcEnginePower
