### ISSUE TITLE
Remove obsolete bindings

### ISSUE THREAD

**Issue by photon1503** [andreasdahl1987/DahlDesignProperties#41]
This should be removed
<img width="594" alt="image" src="https://user-images.githubusercontent.com/14548927/204155877-94088d79-7dc7-4774-ae3f-4c663303af3f.png">

Took me a while to find the new ones ;-)

**Comment by andreasdahl1987** [comment]
Fixed in commit [1cf80bb](https://github.com/andreasdahl1987/DahlDesignProperties/commit/1cf80bbdabff5b1ecb4863e1382aff6873e27b1d)
