### ISSUE TITLE
Delta doubles

### ISSUE THREAD

**Issue by andreasdahl1987** [andreasdahl1987/DahlDesignProperties#43]
Calculations with doubles on lap time deltas will push decimals like 75.98999999999999 to the .CSV file. I think it might be better to round them off or use a different type, will make the .csv a litt prettier at least.

**Comment by photon1503** [comment]
In LapRecords.cs, we coud create a new method

```
        public string JoinFormat(List<double> _deltas)
        {
            string formatString = "{0:D3}";
            string separator = ",";
            return string.Join(separator, _deltas.Select(item => string.Format(formatString, item)));
        }
```

and call this one where the deltas are currently joined.
`            allLines[index] = track + "," + car + "," + Convert.ToString(lapTime) + "," + string.Join(",", deltas);`

Cannot really test it, but this would be a suggestion.

**Comment by andreasdahl1987** [comment]
Good idea! I'll test it :)
