### ISSUE TITLE
Pit entry indicator doesn’t work on Oval, where there are no pit limiters

### ISSUE THREAD

**Issue by teknologika** [andreasdahl1987/DahlDesignProperties#62]
Hey Andreas,

A feature request … Oval cars don’t have pit limiters :-) and pit entry indicator worked a treat during D24, would love to be able to use this for the upcoming Daytona 500, on a wheel with no buttons  :-(

Bruce

https://github.com/andreasdahl1987/DahlDesignProperties/blob/6c61e69e93ac3ddd97e9ba49972797ab8ddc66d2/iRacing/iRacing.cs#L3221

**Comment by andreasdahl1987** [comment]
@teknologika 
This is an area for improvement indeed. Also for popular road cars like the Formula Vee this is relevant. I found telemetry in the irsdk_Trkloc bitfield that might make this work without pit limitlimiter, Ill have a look at it.

**Comment by andreasdahl1987** [comment]
[DahlDesign.zip](https://github.com/andreasdahl1987/DahlDesignProperties/files/10523200/DahlDesign.zip)

I havent got the option to test anything at the moment, but try and see if this works  :)

**Comment by andreasdahl1987** [comment]
@teknologika Still waiting for your response

**Comment by teknologika** [comment]
@teknologika Cloning now ..

**Comment by teknologika** [comment]
Works a treat ... closing
