### ISSUE TITLE
Build Pipeline

### ISSUE THREAD

**Issue by photon1503** [andreasdahl1987/DahlDesignProperties#9]
Hi guys,

I tried to create a github actions build pipeline to compile the release artifact.

But there are some pitfalls
- We need to use windows-2019 as build server, because .NET 4 is not included in the more recent windows VM's
- Upgrading the project to current dotnet version seems unreasonable, since SimHub also uses .NET 4.8 Framework
- The build fails, because several referenced  libraries are missing.

Some of the missing libraries, which are available as nuget package, could be added by adding them to packages.config (i.e. iRacingSDK, MahApps, log4net). But some of them are propertiary like ACSharedMemory, SimHub.Plugins exist only in the local SimHub folder.

Any ideas?
[Link to YAML file](https://github.com/photon1503/DahlDesignProperties/blob/master/.github/workflows/dotnet.yml)

![image](https://user-images.githubusercontent.com/14548927/199809932-2e8e21e9-4f28-4d59-8b03-a12453a868e1.png)

**Comment by andreasdahl1987** [comment]
This would be really great if we could achieve, but I'm afraid I'm of no use here 😞 @mcowger ?

**Comment by mcowger** [comment]
We could potentially add a custom action that downloads the Simhub Exe and extracts what's needed.

**Comment by mcowger** [comment]
I think I've found a solution. I found a way to extract the files from Simhub installer. 

Will share more later

**Comment by mcowger** [comment]
Thanks to @photon1503's skeleton, I was able to get this working!

Next step will be the speed up the build a little with GitHub caches, but its totally functional now.

**Comment by photon1503** [comment]
Thank you @mcowger for the effort!
